version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - pip install --upgrade pip
            - pip install -r requirements.txt
            - echo "Running all unit tests"
           # - pylint -j 0  --disable=W,C,E,R $CODEBUILD_SRC_DIR/*.py
           # - pylint -j 0  --disable=W,C,E,R $CODEBUILD_SRC_DIR/docugoapp/*.py
    pre_build:
        commands:
            - python --version
    build:
        commands:  
            - python --version
artifacts:
    files:
        - '**/*'
